sudo: false
language: node_js
node_js:
- node
- '8'
- '7'
- '6'
- '5'
- lts/*
branches:
  only:
  - MySolace
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- npm install gulp
script:
- nyc npm test && nyc report --reporter=text-lcov | coveralls
- gulp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  matrix:
  - secure: X4zgmS0Scr1mExfHoXb3echeHDhTN3HVG4V/MMPibvgi/If217bJSz8tBhfBia3rBCmlWMIhCqB68yvkHvfcgXrhwKMStW+B+a5wWr468+0hTl3PSuMj8sgJSgcMIqAEfkmDJ9pth5e5QzTuGiMcOzRlvkLrZeiYfVcft0/ppyMZOrQ4R6nuUkP9ozFOg3g5hre/rE+PacOGyOjaAzOPiCENLeMFoRHnaKeomE8RN1XApKahHwJb5ePKdLvmq9dreDqYLiSNWzjnsKzWyZ9VnqntPCSvSBx0aY2iJ3/smZemIxCE/yZPEEhB2yY59JR+52pSO0T11lePtvXkq5ox4A1ZzJ3Cy8mzMwU7LBTZaHUVC+uavPf4FJK8rDb5RTC/lJo81ldYN3VtmTXOwcNSo6o3o69Tryi0PXRRD6P99r5qakSpX18mtALn7xSOABDCt+kg4PiquRuCmGaRJKWL9MlanMACRiwB50U4G4mrsno43lHvSwaQ4gZj+iJLYPbim9GmHtrqhUdoAql+F1befAiLuXv9e3j3KiFkUOZpsvOVIuzELAz9a8qsgM/7Zv6b6oJLisyMPhgyr8ZtIOwSLA+o0kKPK2odg56c9IM3zTHwhhcqZFayxXt51Vrc5G8d+SRPOeMDkzZOCC8dSVmc1euASRSrWf7YF2mGxFXESIY=
  local_dir: "./app"
  name: Deploy
  email: casey@mysolace.life
  project_name: Crisis Trends
  on:
    branch: gh-pages
env:
  - secure: ooGceTqJxzZddJjuiCzx7XPr/53CLgDczxRwspgq91Pe7KKLisg7hIXVOjwmg/VX/Plsox/edRJUUiYMtbogaTMyVEhnZ6S3xsFyCbKmh1DoNhEBNnHTjH2zltuBCcWoXRQrnCJFYou1s7F60khUPDul4CVaHK+9LBLkezdj3dY7UUlcxKR2xwr6DGxOLjf1fDqgG/s6iL/81/3adV3VQnSPqOVuqstF5iOQXPfu2Il0cmqj+twdtqHB8a9AUZDWNbwifBmTcHq0j4bjmODqYyi3GbFmcgw2WecWtB0FxUFm9d7WO3Sus1oGNZpTTMd3cuIC7j4bcBjyXJG1dFuVx8STv8ppAfNTj+IM8X85gmd6FGhWC4gZQvKkliK4zVjYGIImVdMKrBlrOHwuBZppMvS1M8b1AKwRb/7Bd5lhNLoYcLh4H5qWvhc7hVxpvkcI+Y9V97LpQ+Ksrw10vlmL8X6/f3EJGwGpWmdxeeUyHwXcCy8zBTwc8HdgR9tUOQKtjPNo8w6QqV1wzinBEpQcZtUNSuCcbM1CcMT/h8QY4fZFkShDD6hDPW2kDGn+vDjHimVOEgb7Byx96PSO03FDhYBmkuFWTfI8dMJm0SF43L2ipq64Ph6PcpwbEZkALD6+7TvKk4GGMov23fU1oGH4RJj2qqG3r+O5GKqJMFnW6LU=
