sudo: false
language: node_js
node_js:
- node
- '8'
- '7'
- '6'
- '5'
- lts/*
branches:
  only:
  - MySolace
cache:
  directories:
  - node_modules
before_script:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- npm install gulp nyc
script:
- nyc npm test && nyc report --reporter=text-lcov | coveralls
- gulp
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "./app"
  name: Deploy
  email: casey@mysolace.life
  project_name: Crisis Trends
  on:
    branch: gh-page
env:
  github_token: "$GITHUB_TOKEN"
  repo_token: "$REPO_TOKEN"
