sudo: false
language: node_js
node_js:
  - node
  - lts/*
branches:
  only:
  - MySolace
cache:
  yarn: true
  directories:
  - node_modules
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn
  - npm install gulp --save-dev
  - gulp
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "dist"
  name: Deploy
  email: casey@mysolace.life
  project_name: Crisis Trends
  on:
    branch: gh-pages
env:
  github_token: "$GITHUB_TOKEN"
  repo_token: "$REPO_TOKEN"
